Repository ultralytics/hub, pull requests merged in 2024-11, with the labels that each got.

#917 Fix PyPI downloads links
  hub.ipynb
Labels: documentation, enhancement, app

#919 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: enhancement, devops

#920 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: devops

#930 Update ci.yaml for Slack v2
  .github/workflows/ci.yaml
Labels: enhancement, devops

#933 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement
