Repository ultralytics/hub, pull requests merged in 2025-01, with the labels that each got.

#967 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#974 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#980 Rename `ci.yaml` to `ci.yml`
  .github/workflows/ci.yml
  .github/workflows/links.yml
  README.md
  README.zh-CN.md
  hub.ipynb
Labels: documentation, devops

#984 Standardize license headers in TOML/YAML files
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/links.yml
  .github/workflows/stale.yml
  example_datasets/coco8-human/coco8-human.yaml
  example_datasets/coco8-pose/coco8-pose.yaml
  example_datasets/coco8-seg/coco8-seg.yaml
  example_datasets/coco8/coco8.yaml
  example_datasets/dota8/dota8.yaml
Labels: documentation, devops

#1001 Use uv pip install
  .github/workflows/ci.yml
Labels: dependencies, devops, pip

#1004 Update links.yml
  .github/workflows/links.yml
Labels: enhancement, devops
